#!/bin/bash

#$1 is the timeout

params=(1 2 4 8 16 32 64 128 265)

for i in {0..8}
do
    for j in {0..4}
    do
        python3 Sender3.py localhost 1234 test.jpg $1 ${params[$i]}
        sleep 1s
    done
    echo ""
done
